#%RAML 1.0 NamedExample

  value:
  
  - addressid: 201
    amount: 300
    created: 
      type: datetime
      date: 2016-02-28T16:41:41.090Z
  
  - discountid: 202
    modified: 
        type: datetime
        datetime: Sun, 28 Feb 2016 16:41:41 GMT
        format: rfc2616
  
  - orderid: 203
    status: active
    userid: 04
    
  