#%RAML 1.0 NamedExample

value:
  productid: 101
  category: tablet
  name: iPad Pro
  description: The 11-inch iPad Pro display has rounded corners, curved design. The screen is 11 inches diagonally   (actual viewable area is less).
  video_url: https://www.apple.com/ipad-pro
  price: 799