#%RAML 1.0 NamedExample
value:
-
  categoryid: 101
  description: MacBook Pro
  name: Laptop
  price: 1700
  SerialNumber: FVb3421QM0Y
  video_url: https://www.apple.com/shop/buy-mac/macbook-pro/13-inch

-
  categoryid: 107
  description: MacBook Air
  name: Laptop
  price: 1200
  SerialNumber: ER345M0ND
  video_url: https://www.apple.com/shop/buy-mac/macbook-air/13-inch

